name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: npm build
      run: |
          npm install
          npm run build
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "main.js,manifest.json,versions.json,styles.css"
        omitBody: true